- mcs_docker_setup/analysis-ui/src/components/App/scenesEval3.jsx
- mcs_docker_setup/node-graphql/server.mongoSyntax.js
- mcs_docker_setup/node-graphql/server.schema.js
Opening new PR for MCS-515. Scores table is using Material UI and now has sorting. 
I also messed with the fields/labels we're displaying in the scores table (removed MSE and renamed 'Answer' to 'Classification'), and added back in the complexQuery to display the slices data within the scores table.
> MCS-515 - Add sorting to scores table

- mcs_docker_setup/analysis-ui/src/components/App/scenesEval3.jsx
- mcs_docker_setup/analysis-ui/src/css/app.css
Right now, just displaying everything in one big table that we can iterate on/cleanup later -- added an expand/collapse since the list can get a bit long for agency tasks.
Also, retitled "Answer" header in both tables to "Classification". 
Columns displayed: Step Number, Action, Classification, Confidence, Violations ((x,y) list)
(Didn't make this dependent on the MCS-524 table changes, but in case MCS-524 is merged before this, I can update this PR to use that table component instead).
> MCS-524 - Initial table for classification by step

- mcs_docker_setup/analysis-ui/src/components/App/commentsDisplay.jsx
- mcs_docker_setup/analysis-ui/src/components/App/header.jsx
- mcs_docker_setup/analysis-ui/src/components/App/index.jsx
- mcs_docker_setup/analysis-ui/src/components/App/queryResultsTable.jsx
- mcs_docker_setup/analysis-ui/src/components/App/scenes.jsx
- mcs_docker_setup/analysis-ui/src/components/App/scenesEval3.jsx
- mcs_docker_setup/node-graphql/server.fieldMappings.js
- Eval name is no longer hardcoded from queryResultsTable
- Corrected scene_num parameter to "test_num" in URL and added "scene" parameter to allow for selecting a particular scene via links
This is still a bit goofy because:
1.) The scene_num fields still need to be fixed in ingest (I created another ticket for that somewhere and I thought it was safer not to try to do this all at once)
2.) The way people want to select and view different tests + scenes/manage that state will probably factor into some analysis UI page redesign at some point since it is currently spread around about 3 or 4 components right now, which isn’t ideal IMO.
> MCS-514 - Fix analysis UI URLs/test vs scene references

- analysis-ui/src/components/Analysis/displayTextUtils.js
- analysis-ui/src/components/Analysis/sceneDetails.jsx
- analysis-ui/src/components/Analysis/scenes.jsx
- analysis-ui/src/components/Analysis/scenesEval3.jsx
- analysis-ui/src/components/Analysis/scoreTable.jsx
- analysis-ui/src/css/app.css
- A modal for scene details/download has been added to the score table.
- You can now select the score table row to select a scene, instead of using a button. 
- Some refactoring -- most notably score table and details are now separate components.
> MCS-517 - [Analysis UI Page] Move scene info/objects in scene details to a modal

- node-graphql/server.schema.js
This has a companion ticket in mcs-ingest that actually drops the collection from the database, along with setting up the framework for deployment scripts to be run.
> MCS-583: Remove usage of old keys collection from codebase

- analysis-ui/src/components/Analysis/header.jsx
- analysis-ui/src/components/Analysis/scenes.jsx
- analysis-ui/src/components/App/index.jsx
- node-graphql/server.schema.js
- Fixing places where we were checking for eval 2 code with "includes("2")" (I used that when we weren't really sure about naming conventions, but now we can reliably use "Evaluation 2 Results")
- Likewise, removing anything specifically looking for eval 3 like "includes("3")" from the header dropdown on the Analysis UI page so that future evals like Eval 4 still work. 
- Adding eval argument to the history/scene queries, so we're not just depending on category type/test type and number
- Fixed a bug with eval regex in server.schema
> Fixes for evaluation references on homepage/header drop downs

- analysis-ui/src/components/Analysis/evalConstants.jsx
Putting S3 behind CloudFront/Route 53 DNS/subdomain, also needed for MediaConvert Lambda function.
> MCS-615: Update bucket URL 

- analysis-ui/src/components/EvaluationStatus/evalStatusPage.jsx
The eval status page will update every second if you are on the page so it will constantly rerender the updates on our process so no need to have a button as well.
> MCS-764:  Update Eval Status Page every second automatically

- analysis-ui/src/components/QueryBuilder/fieldDropdown.jsx
- analysis-ui/src/components/QueryBuilder/fieldValuesDropdown.jsx
- analysis-ui/src/components/QueryBuilder/saveQuery.jsx
- analysis-ui/src/css/app.css
There is a "Combine All" option to combine all the query parameters across the different queries. The z-index style and css i added because the sticky header for the table seems to overlap the dropdowns for the query searches. I felt that was a bug fix somewhat related to the task so I fixed it. The only way to fix that z-overlap in some cases was the apply it directly to the component.
> Name suggestion based on Query Parameters for save query results

- analysis-ui/src/components/QueryBuilder/loadQuery.jsx
- analysis-ui/src/css/app.css
I also changed the load query to be 50 percent of viewport height because I felt it was too small especially on larger montiors
I realized halfway through this that this ticket was supposed to be for the actual table and not load query. So I changed that old ticket to reflect this load query search bar change and made a new ticket for the original results table task here: https://nextcentury.atlassian.net/browse/MCS-856?atlOrigin=eyJpIjoiNWRmNTlkZjExY2I4NDg0OGE2ZjkzOWQ4OThhYTM4NjEiLCJwIjoiaiJ9
> Load Query Search Bar

- analysis-ui/src/components/Analysis/scenes.jsx
One line change -- I think this contains query on category for getting the history records per test may cause issues now that we have things like "interactive object permanence" vs "object permanence", so wanted to address it now.
> Fix scene history query for analysis UI page for Eval 4

- analysis-ui/src/components/Analysis/scenes.jsx
Found this a couple days ago when playing with dev graphql -- it looked like there were duplicates at first, but then realized I likely need an extra clause to specify which scene data to pull since we're sharing names/descriptions for things in Eval 4. 
Now that I'm looking at this again, I'm wondering if there's something with the complex query itself that should be updated instead (I was able to do something similar in dev on the Query Builder page to demonstrate, if you examine the scene info on the query I saved in dev for "MESS golf Eval 4 Results Query", but that could also be user error since I only used history collection fields and not one from "scene" as well).
> Analysis query fix

- analysis-ui/src/components/Analysis/scenes.jsx
- analysis-ui/src/components/Analysis/scoreTable.jsx
- node-graphql/server.schema.js
Abandoning using createComplexQuery on the scene analysis page and switching to a more accurate query for scene history (using eval, category_type, and test_num).
> MCS-1009 Fix scene history query on analysis UI page

- analysis-ui/src/components/Analysis/sceneDetails.jsx
- analysis-ui/src/components/Analysis/scenesEval2.jsx
UI should link correctly for eval 4 *_debug.json files now + snuck in a fix for the score table for eval 2 scenes.
> Fixing debug file names for non-agency scenes (MCS-970).

- analysis-ui/package.json
- analysis-ui/src/components/TestOverview/hypercubeResultsTable.jsx
- analysis-ui/src/components/TestOverview/overview.jsx
- analysis-ui/src/css/app.css
- node-graphql/server.schema.js
- node-graphql/server.statsFunctions.js
Below you can see that we added new columns for do not answer for plausible and implausible, currently with the toggle they are included in the calculations:
Turning the toggle you can now see they are no longer included and the Total tests goes down appropriately.
> MCS-1060:  Add do not answer and toggle to Test Overview

- analysis-ui/src/components/Analysis/classificationByStepTable.jsx
- analysis-ui/src/components/Analysis/scenes.jsx
This ticket adds FPS and delta milliseconds (real time between actions) to the step table.  This also makes that table visible for interactive however it excludes columns that are only pertinent for intuitive physics from the interactive view.
NOTE:  This ticket is based on MCS-841 so it will merge sometime after the PI Meeting.
> MCS-636:  Add FPS to UI

- analysis-ui/src/components/EvaluationStatus/evalStatusTable.jsx
- node-graphql/package.json
- node-graphql/server.schema.js
This was to prevent polluting the console with 404-related errors if a csv file hasn't yet been generated.
> Move csv check to node-graphql using url-exist dependency (MCS-935).

- analysis-ui/src/components/Analysis/scenes.jsx
- analysis-ui/src/components/Analysis/scoreTable.jsx
We're using the prefix of the name of scenes to query on the scene analysis view. It was only using everything up to the first underscore, which is obviously a problem for something like "eval_5_validation_scene_whatever_0001_01". Should now be using everything up to the second to last underscore. 
Also noticed we were relying on all scenes being present, but we have partial hypercubes for validation data.
> Fix scene query on analysis view.

- analysis-ui/src/components/Analysis/scenes.jsx
- analysis-ui/src/components/Analysis/scoreTable.jsx
- analysis-ui/src/css/app.css
The table now scrolls with a fixed header. The position of the highlighted current scene will always be in view of the table window. This is helpful especially for the play all feature as the table scrolls with the videos as you play through each scene moving down the table.
> Cube results table scrolls with videos

- analysis-ui/src/components/QueryBuilder/loadQuery.jsx
- analysis-ui/src/components/QueryBuilder/queryPage.jsx
- analysis-ui/src/css/app.css
- analysis-ui/src/services/config.js
First time touching React since August so I was a little rusty but I think this turned out good. I added a bonus of rows being highlighted when you hover over them so you know that you are going to select it and that you can click the entire row, not just the checkbox to make a selection. David wanted alternating rows to be  slightly different colors so that's the case for both unselected (white/light-grey) and selected rows (light-blue/dark-blue).
Selecting one query will replace the current query tab. Selecting more than one query will append multiple queries to the end of the tab list.
Here is a screenshot of the original design idea from zeplin that I tried to match.
> Load Query Redesign

- analysis-ui/src/components/Analysis/scorecard.jsx
- analysis-ui/src/components/TestOverview/hypercubeResultsTable.jsx
- analysis-ui/src/components/TestOverview/scorecardTable.jsx
- analysis-ui/src/css/app.css
- node-graphql/server.schema.js
Ingest PR here: https://github.com/NextCenturyCorporation/mcs-ingest/pull/98
Making sure all current scorecard fields for Eval 5 are displaying properly in the UI (on scene analysis as well as test overview). Also incorporated the walked_into_structures scorecard field thats still in PR. 
Edit: Realized I should probably add screenshots:
Test overview page:
Scene analysis page popup:
> MCS-1349 scorecard updates

- analysis-ui/src/components/QueryBuilder/deleteQuery.jsx
- analysis-ui/src/components/QueryBuilder/loadQuery.jsx
- analysis-ui/src/components/QueryBuilder/queryBuilder.jsx
- analysis-ui/src/components/QueryBuilder/queryPage.jsx
- analysis-ui/src/components/QueryBuilder/saveQuery.jsx
- analysis-ui/src/components/QueryBuilder/updateQuery.jsx
- analysis-ui/src/css/app.css
- node-graphql/server.schema.js
You can delete multiple queries from load query if they are tied to your account. Once a query tab is loaded, if that query is tied to your account you can update or delete it alongside clearing it and saving a new one. 
Updating gives you the option to only change the name and description but not the contents if you want. This is so you can add or remove properties from your query and change the groupby and sortby without overwriting those when you update. I found this is more useful for changing groupby and sortby. 
Active query tabs that are tied to the same mongo id as the query  being updated or deleted will be modified accordingly. So if I had 10 tabs loaded and open for the query "Jacob Test 1" and deleted that query from the load query delete modal, all of those tabs will be …
> Query Page Delete and Update

- analysis-ui/src/components/TestOverview/hypercubeResultsTable.jsx
- analysis-ui/src/components/TestOverview/overview.jsx
- analysis-ui/src/css/app.css
- node-graphql/server.schema.js
- node-graphql/server.statsFunctions.js
Modified Test Overview to have tabs for cube id/slice/scorecard - only show tab and table if applicable to that test/category type.  Made it so on the slice view, you can view by slice levels.
> MCS-1198: Add view to test overview to be able to view by slice and slice levels

- analysis-ui/src/components/TestOverview/overview.jsx
I thought there would be more than one place we were using the "retrieval" flag but this is the only place in the front end or back end UI code.
> MCS-1135:  Update any 'retrieval' checks to include 'multi retrieval'

- analysis-ui/src/components/Home/chartContainer.jsx
- analysis-ui/src/components/Home/homeCharts.jsx
- node-graphql/server.schema.js
Added a fix for landing page "passive agents" should not show "paired/unpaired" like it used to do for "agents"
> MCS-1716:  Fix issue with duplicate charts on landing page

- analysis-ui/Dockerfile
- node-graphql/Dockerfile
Realized that node-graphql failed to rebuild this morning because the old base image is using a (now) archived version of Debian. Upgraded from node:12 to node:14 (which uses Debian 10 instead of 9).
> MCS-1786 - update base image in Dockerfiles

- node-graphql/csv-scripts/generate_csv.py
Fix for csv creation in dev environment.
> Get correct db_string for csv creation (either 'dev' or 'mcs').

- analysis-ui/src/components/Home/chartContainer.jsx
- node-graphql/server.statsFunctions.js
Should have weighted/unweighted toggle now for Passive Agency for Eval 6+ on the home page charts, but will only work for seeing leads to knowing. The other passive agency tasks will always be represented as weighted (or paired in this case).
Note that this was branched off of MCS-1786.
> MCS-1780 - Add weighted toggle for seeing leads to knowing on home page

- analysis-ui/src/components/Analysis/navigation.jsx
- analysis-ui/src/components/Analysis/scorecard.jsx
- node-graphql/csv-scripts/generate_csv.py
MCS-1429 specific changes are in generate_csv.py. Messed with different cache-control settings (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) so that the csv file response doesn't get reused. Seems like you need to do it upfront (before you've ever created a file) and on upload for it to work correctly + our current csvs wouldn't have any updates at this point anyway, so I tested by using a separate local test script creating a new test csv file to upload to dev-evaluation-images with the cache-control setting specified, and making minor updates to the csv file each time.
The fixes in the other analysis-ui are minor things like getting rid of console.log / Unique "key" prop errors, and making sure the categories are capitalized in the Scene Analysis view like …
> MCS-1429 - Fix for updating csv file links + minor UI fixes

- node-graphql/csv-scripts/generate_csv.py
Originally tried to do this on the ingest side via collection keys, but I realized that would impact the query builder as well, so made it csv specific.
Now the csv won't have any steps array fields besides the fields in "STEPS_OUTPUT_FIELDS_TO_SAVE", since mongoexport isn't exporting them anyway. To save the first element for all these fields, it just has to be specified explicitly (so "steps.0.output.position.x" instead of "steps.output.position.x").
> MCS-1804 - For results CSV, save performer position/target info from first element in steps array

- analysis-ui/src/components/Analysis/scoreTable.jsx
Added a default sortby in SortTable.  Seems to default sorting by scene_name ascending in Firefox now.  Retested in Chrome, didn't see any issues.
> MCS-1828set default to sorting for firefox

- node-graphql/server.fieldMappings.js
Minor change needed to see the start_distance_between_performer_and_target field within the UI
Ingest PR here: https://github.com/NextCenturyCorporation/mcs-ingest/pull/139
> MCS-1956 - Make new distance field visible within query builder

- node-graphql/server.fieldMappings.js
(Note that this was branched off of MCS-1956).
Once again, if the fields aren't appearing in the scenes CSV file when we actually run the eval, we'll just need to run the update_collection_keys_if_missing.py on the ingest side (I ran this locally to test). Verified that the tags mentioned in this ticket are already saved in ingest properly within the scene record, these minor changes here are just needed so that Koleen will also be able to see + query on these fields in the query builder.
> MCS-1965 - Adding important tags for Set Rotation in Eval 7

- analysis-ui/src/components/TestOverview/scorecardTable.jsx
- node-graphql/server.schema.js
See ingest PR here: 
https://github.com/NextCenturyCorporation/mcs-ingest/pull/140
On the Test Overview page, I put the values next to the other tool use ones as opposed to adding them to the end of the list, in case anyone has trouble finding them.
> MCS-1971 - Incorporate new scorecard values for eval 7 
