mcs_docker_setup/analysis-ui/src/components/App/myAccount.jsx
mcs_docker_setup/analysis-ui/src/css/app.css
mcs_docker_setup/analysis-ui/src/css/my-account.css

Also added placeholder disabled inputs for now for username/email.
@brianpippin let me know if I missed anything for this ticket.

MCS-458: Add ability to change password to 'My Account' page

---

mcs_docker_setup/analysis-ui/src/components/App/fieldDropdown.jsx
mcs_docker_setup/analysis-ui/src/components/App/fieldValuesDropdown.jsx
mcs_docker_setup/node-graphql/server.schema.js

Yes I know i mistyped the branch as MC-508 i'll just delete it after merging :)

MCS-508: Field field drop downs in query builder based on collection

---

mcs_docker_setup/analysis-ui/src/components/App/performanceStatistics.jsx
mcs_docker_setup/analysis-ui/src/components/App/queryResults.jsx
mcs_docker_setup/analysis-ui/src/components/App/queryResultsTable.jsx
mcs_docker_setup/analysis-ui/src/css/app.css

Adding some metrics to query results giving the psychologists extra information.

MCS-523: Add some performance metrics to the table results

---

analysis-ui/src/components/App/index.jsx
analysis-ui/src/components/EvaluationStatus/evalStatusConfigure.jsx
analysis-ui/src/components/EvaluationStatus/evalStatusPage.jsx
analysis-ui/src/components/EvaluationStatus/evalStatusTable.jsx
analysis-ui/src/components/Home/homeCharts.jsx
analysis-ui/src/components/QueryBuilder/performanceStatistics.jsx
analysis-ui/src/css/app.css
node-graphql/server.schema.js

Show the progress of the evaluation

MCS-587: Add a configurable Evaluation Status Page

---

analysis-ui/src/components/Analysis/evalConstants.jsx

Still need to update triggers for automated ingest (see comment).

Constants update for gravity rerun (MCS-646).

---

analysis-ui/public/configs/prod/config.js
analysis-ui/public/configs/prod/graphql-config.js
docker_setup/README.md
homepage/index.html

MCS-617 & 605:  Code to allow for us to use subdomain urls and add https functionality.

Update urls to use domains

---

analysis-ui/src/components/EvaluationStatus/evalStatusPage.jsx
analysis-ui/src/components/EvaluationStatus/evalStatusTable.jsx

MCS-764:  Fix table not rerendering

---

analysis-ui/Dockerfile
docker_setup/docker-compose.yml
node-graphql/Dockerfile

Upgrade to Node 12 and increase swap space.

MCS-831: Fix for memory allocation error on prod

---

analysis-ui/package.json
analysis-ui/src/components/QueryBuilder/performanceStatistics.jsx
analysis-ui/src/components/QueryBuilder/queryResults.jsx
analysis-ui/src/components/QueryBuilder/queryResultsTable.jsx
analysis-ui/src/css/app.css

This only downloads data the query results table shows. The json data for each row has a lot more data for score and scene information but it wasnt shown on the table so i filtered it out.

CSV download from query results table

---

analysis-ui/package.json
analysis-ui/src/components/Analysis/interactiveScenePlayer.jsx
analysis-ui/src/components/Analysis/playbackButtons.jsx
analysis-ui/src/components/Analysis/scenes.jsx
analysis-ui/src/components/Analysis/scenesEval2.jsx
analysis-ui/src/components/QueryBuilder/fieldDropdown.jsx
analysis-ui/src/components/QueryBuilder/fieldValuesDropdown.jsx
analysis-ui/src/components/QueryBuilder/performanceStatistics.jsx
analysis-ui/src/components/QueryBuilder/queryResults.jsx
analysis-ui/src/components/QueryBuilder/queryResultsTable.jsx
analysis-ui/src/components/QueryBuilder/saveQuery.jsx
analysis-ui/src/css/app.css

Merge Jacob's CSV table download, playback buttons, and query name suggestion into master

Merge Development into Master

---

analysis-ui/src/components/Analysis/playbackButtons.jsx
analysis-ui/src/components/QueryBuilder/loadQuery.jsx
analysis-ui/src/components/QueryBuilder/queryBuilder.jsx
analysis-ui/src/components/QueryBuilder/queryPage.jsx
analysis-ui/src/components/QueryBuilder/queryResults.jsx
analysis-ui/src/components/QueryBuilder/queryResultsTable.jsx
analysis-ui/src/components/QueryBuilder/saveQuery.jsx
node-graphql/server.schema.js

Run these first to make it work. I also updated the csv naming. I had to change some functional components to class components to forward the ref because the ref would become undefined if they were different. 
```
docker build --tag node-graphql node-graphql/.
docker build --tag node-graphql-staging node-graphql/. --build-arg PORT_ARG=9111
```

Save sorting and grouped by options to saved query

---

analysis-ui/public/configs/dev/config.js
analysis-ui/public/configs/dev/graphql-config.js
analysis-ui/public/configs/dev/graphql-staging-config.js
analysis-ui/public/configs/dev/staging-config.js
analysis-ui/public/configs/prod/config.js
analysis-ui/public/configs/prod/graphql-config.js
analysis-ui/public/configs/prod/graphql-staging-config.js
analysis-ui/public/configs/prod/staging-config.js
analysis-ui/src/components/Analysis/evalConstants.jsx
analysis-ui/src/components/EvaluationStatus/evalStatusTable.jsx
docker_setup/resources/mongo-init.js
node-graphql/csv-scripts/generate_csv.py
node-graphql/server.mongo.js
node-graphql/server.schema.js

Setting up a dev databases and configuring our staging/dev server to utilize it along with all of the created AWS resources to go with it.

MCS-735: Code for dev/staging to use different mongo db and resources

---

analysis-ui/src/components/Analysis/classificationByStepTable.jsx
analysis-ui/src/components/Analysis/plausabilityGraph.jsx
analysis-ui/src/components/Analysis/scenes.jsx
analysis-ui/src/css/app.css

Resurrecting old plausibility chart (thanks to Brian for already creating that component). Also made videos smaller to fit plausibility chart in at the top per mockups. May need to revisit sizing later depending on how the data looks. 
This was branched from the navigation changes, hence the base branch.

MCS-511 - Plausibility Graph 

---

analysis-ui/src/components/Analysis/scenes.jsx
analysis-ui/src/components/Analysis/scoreTable.jsx
analysis-ui/src/components/Analysis/scorecard.jsx
analysis-ui/src/components/QueryBuilder/queryResultsTable.jsx
analysis-ui/src/components/TestOverview/hypercubeResultsTable.jsx
analysis-ui/src/components/TestOverview/scorecardTable.jsx

Fix csv formatting
Fix unused includes
Fix interactive videos under table
Remove blank constructor

MCS-1007: Scorecard on analysis and other fixes

---

analysis-ui/package.json
analysis-ui/src/components/QueryBuilder/fieldValuesDropdown.jsx
analysis-ui/src/components/QueryBuilder/queryBuilder.jsx
analysis-ui/src/components/QueryBuilder/queryLine.jsx
node-graphql/server.mongoSyntax.js
node-graphql/server.statsFunctions.js

Add to query builder an Input field for equals - make default to improve load speed

MCS-1028: Add ability to do an equals with an input field

---

analysis-ui/src/components/Analysis/evalConstants.jsx
analysis-ui/src/components/Analysis/scenes.jsx

Linking to the most recent log file (matching the history file timestamp) in the UI.

Add link to log file to UI (MCS-887).

---

analysis-ui/src/components/Analysis/evalConstants.jsx
analysis-ui/src/components/Analysis/navigation.jsx
analysis-ui/src/components/EvaluationStatus/evalStatusConfigure.jsx
analysis-ui/src/components/EvaluationStatus/evalStatusPage.jsx
analysis-ui/src/components/EvaluationStatus/evalStatusTable.jsx
analysis-ui/src/components/Home/home.jsx
analysis-ui/src/components/QueryBuilder/fieldDropdown.jsx
analysis-ui/src/components/QueryBuilder/fieldValuesDropdown.jsx
analysis-ui/src/components/QueryBuilder/queryLine.jsx
analysis-ui/src/components/QueryBuilder/queryResults.jsx
analysis-ui/src/components/QueryBuilder/queryResultsTable.jsx
analysis-ui/src/components/TestOverview/evalNavItem.jsx
analysis-ui/src/components/TestOverview/hypercubeResultsTable.jsx
node-graphql/server.mongoSyntax.js
node-graphql/server.schema.js

This is the companion ticket for ingest MCS-841.  This code updates the UI to utilize the new structure where each eval has its own collection for results and scenes.

MCS-841:  Update code for database refactor

---

analysis-ui/src/components/Analysis/interactiveScenePlayer.jsx
analysis-ui/src/components/Analysis/navigation.jsx
analysis-ui/src/components/Analysis/scenes.jsx
analysis-ui/src/components/Analysis/scenesEval2.jsx
analysis-ui/src/components/Analysis/scoreTable.jsx
analysis-ui/src/components/App/index.jsx
analysis-ui/src/components/QueryBuilder/queryResultsTable.jsx
analysis-ui/src/components/TestOverview/evalNavItem.jsx
node-graphql/server.schema.js

Analysis UI page update: removing rating and score columns from score table for interactive scenes since they don't apply there.

Remove rating/score columns for interactive scenes (MCS-621).

---

analysis-ui/src/components/TestOverview/scorecardTable.jsx

~~There may be other fixes needed beyond renaming the column.~~
EDIT: I think I fixed all of the other issues in the `mcs-ingest` code: https://github.com/NextCenturyCorporation/mcs-ingest/pull/99

Renamed Correct Platform Side scorecard column.

---

analysis-ui/src/components/Analysis/sceneDetails.jsx

Links to debug files for each scene aren't working currently, wanted to get this in for when people start looking at specific results/scenes.

Fix links for scene debug files for Eval 5+.

---

analysis-ui/src/components/Analysis/sceneDetails.jsx

Forgot all about eval 2 in my recent update (oops!)

Fix eval 2 scene link

---

analysis-ui/src/components/TestOverview/allIncorrectScenes.jsx
analysis-ui/src/components/TestOverview/overview.jsx
analysis-ui/src/css/app.css
node-graphql/server.schema.js

NOTE:  Came up with a totally new way to do this query because looping through the scenes and tests individual was incredibly slow.  Now everything is under 500ms so that seems like a solid improvement.

MCS-1492:  Add tab to test overview that shows all scenes that are incorrect for all performers

---

analysis-ui/src/components/TestOverview/overview.jsx

Thankfully most of the UI is dynamic and not reliant on these goal category types, so few changes.

MCS-1554: Add support for imitation goal type

---

README.md
node-graphql/Dockerfile
node-graphql/csv-scripts/generate_csv.py

Incorporating minor updates I had to make to get things working. 
Also wanted to note this somewhere not in the docs since I feel like it might be new Mac specific: I had to use numpy==1.24.1 for ingest.

Update README + Dockerfile.

---

analysis-ui/src/components/TestOverview/scorecardTable.jsx
node-graphql/server.schema.js

This PR is now ready for review.
Corresponding ingest PR: https://github.com/NextCenturyCorporation/mcs-ingest/pull/112

MCS-1597 Added pickup_non_target scorecard metric.

---

analysis-ui/src/components/Analysis/sceneDetails.jsx

Saw something about this in Slack, I think this is the right naming pattern for eval 6.

Fix debug scene link for Eval 6 scenes.

---

analysis-ui/package.json
analysis-ui/src/components/TestOverview/hypercubeResultsTable.jsx
analysis-ui/src/components/TestOverview/overview.jsx
analysis-ui/src/components/TestOverview/sliceBarChart.jsx
analysis-ui/src/components/TestOverview/sliceBarChartFull.jsx
analysis-ui/src/css/app.css
node-graphql/server.schema.js
node-graphql/server.statsFunctions.js

Chart is underneath table on test overview page for slices/keywords view. ~~Also made the keywords clause an "or" instead of an "and" so they can view data across slice levels.~~

MCS-1598 - new slices chart on test overview

---

node-graphql/server.statsFunctions.js

Small change to add "Total Plausible" and "Total Implausible" columns.

MCS-1772 - Update Test Overview for Seeing Leads to Knowing

---

analysis-ui/src/components/Analysis/sceneDetails.jsx

Updating debug file name case for Eval 7.
Note to self: remember to push to master branch as well.

MCS-1767 - Fixing debug file names for eval 7 data 

---

node-graphql/server.schema.js

Fix for bug Koleen mentioned on Slack.

Fix to display knowledeable agents correctly on test overview.
